name: Build Network Info App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper dh-python python3-tk
    
    - name: Build DEB package
      run: |
        # Executar o script de setup_deb.py
        python setup_deb.py
    
    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: network-info-deb
        path: dist/*.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --noconsole --icon=assets/icone.ico main.py --name network-info
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: network-info-windows
        path: dist/network-info.exe
