name: Build Python Executables for Windows and Linux (deb)

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller upx

      - name: Build executable for Windows
        run: |
          pyinstaller --onefile --name meu-ip --icon=assets/icone.ico --noconsole --strip --compress=upx main.py

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/meu-ip.exe

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller upx
          sudo apt-get update
          sudo apt-get install -y ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build executable for Linux
        run: |
          pyinstaller --onefile --name meu-ip --icon=assets/icone.png --noconsole --strip --compress=upx main.py

      - name: Package executable into .deb
        run: |
          mkdir -p package/usr/local/bin
          cp dist/meu-ip package/usr/local/bin/
          fpm -s dir -t deb -n meu-ip -v 1.0 --prefix=/ package

      - name: Upload Linux .deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-deb-package
          path: package/*.deb

  release:
    needs: [build_windows, build_linux]  # Garante que o release só será criado após o build

    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/meu-ip.exe
            package/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}