name: Build Python Executable

on:
  push:
    branches:
      - main  # Aciona a ação quando você enviar código para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller upx

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --strip --compress=upx seu_script.py  # Substitua 'seu_script.py' pelo nome do seu script

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: executavel-linux
          path: dist/seu_script  
