name: Build Python Executables for Windows and Linux (deb)

on:
  push:
    tags:
      - "v*"

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable for Windows
        run: |
          pyinstaller --onefile --name meu-ip --icon=assets/icone.ico --noconsole --strip main.py

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/meu-ip.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          sudo apt-get update
          sudo apt-get install -y ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build executable for Linux
        run: |
          pyinstaller --onefile --name meu-ip --icon=assets/icone.png --noconsole --strip main.py

      - name: Package executable into .deb
        run: |
          mkdir -p package/usr/local/bin
          cp dist/meu-ip package/usr/local/bin/
          fpm -s dir -t deb -n meu-ip -v 1.0 --prefix=/ package

      - name: Upload Linux .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-package
          path: package/*.deb

  release:
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Download Windows executable
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: dist/

      - name: Download Linux .deb package
        uses: actions/download-artifact@v4
        with:
          name: linux-deb-package
          path: package/

      - name: Debug artifacts
        run: ls -R dist/ package/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/meu-ip.exe
            package/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
