name: Build

on:
  push:
    tags:
      - 'v*'  # Executa o workflow quando uma tag que começa com 'v' é criada

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Windows executable with icon
      run: |
        pyinstaller --onefile --icon=assets/icone.ico main.py --name meu-ip

    - name: Upload Windows executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/meu-ip.exe  # Caminho para o executável gerado

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies for .deb package
      run: |
        sudo apt-get update
        sudo apt-get install -y dh-make build-essential

    - name: Create .deb package
      run: |
        # Cria a estrutura do pacote .deb
        mkdir -p meu-ip/usr/local/bin
        mkdir -p meu-ip/usr/share/icons
        cp main.py meu-ip/usr/local/bin/meu-ip  # Copia o script para o diretório do pacote
        cp assets/icone.png meu-ip/usr/share/icons/meu-ip.png  # Copia o ícone

        # Cria o arquivo de controle do pacote .deb
        mkdir -p meu-ip/DEBIAN
        echo "Package: meu-ip" > meu-ip/DEBIAN/control
        echo "Version: 1.0" >> meu-ip/DEBIAN/control
        echo "Architecture: all" >> meu-ip/DEBIAN/control
        echo "Maintainer: Your Name <you@example.com>" >> meu-ip/DEBIAN/control
        echo "Description: Meu IP - Um programa para verificar o endereço IP" >> meu-ip/DEBIAN/control

        # Constrói o pacote .deb
        dpkg-deb --build meu-ip
        mv meu-ip.deb meu-ip_1.0_all.deb  # Renomeia o pacote

    - name: Upload Debian package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: meu-ip_1.0_all.deb  # Caminho para o pacote .deb gerado
