name: Build Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows (EXE e MSI)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install cx_Freeze
        run: pip install cx_Freeze
        shell: powershell

      - name: Build project (EXE and MSI)
        run: |
          python setup.py build
          python setup.py bdist_msi
        shell: powershell

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: |
            build\**\*
            dist\**\*.msi

  build-deb:
    name: Build Debian Package (.deb)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install stdeb dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-stdeb
          pip install --upgrade pip setuptools wheel
          pip install stdeb

      - name: Build Debian package (.deb)
        run: python setup_deb.py --command-packages=stdeb.command bdist_deb

      - name: Upload Debian artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: deb_dist/*.deb
