name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instalar dependências Python
        run: pip install cx_Freeze

      - name: Build com cx_Freeze
        run: python setup.py build

      - name: Instalar UPX
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install upx -y
          else
            sudo apt-get update && sudo apt-get install -y upx
          fi

      - name: Comprimir Executável com UPX
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            upx --best --ultra-brute build/exe.win*/meu_ip.exe
          else
            upx --best --ultra-brute build/exe.linux*/meu_ip
          fi

      - name: Criar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.os }}
          path: build/*
          if-no-files-found: error