name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install cx_Freeze

      - name: Build with cx_Freeze (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python setup.py build
        env:
          BASE: "Win32GUI"  # Evita a janela do console no Windows

      - name: Build with cx_Freeze (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python setup.py build

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.os }}
          path: |
            build/**  # Inclui todos os arquivos gerados pelo cx_Freeze

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            build/**  # Inclui todos os arquivos gerados pelo cx_Freeze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}